### ISSUE TITLE
Unit testing interceptors/retry policies

### ISSUE THREAD

**Issue by gray419** [CodingAleCR/http_interceptor#45]
I'm building an http client with:

```
    final client = HttpClientWithInterceptor.build(
      interceptors: [
        MyApiInterceptor()
      ],
      retryPolicy: RefreshTokenRetryPolicy(),
    );
```

I'd like to mock a `401` via:

```
    test('test retry policy called twice', () async {
      when(apiClient.post('/path', body: {})).thenAnswer(
          (realInvocation) async => Response('Not Authorized', 401));

      final response = await apiClient.post('/path', body: {});

      expect(response.statusCode, 401);
      verify(tokenService.refresh()).called(2);
    });
```

But I'm getting an error: `type 'Future<Response>' is not a subtype of type 'Future<String>'` .  Any examples or tips would be awesome!

**Comment by CodingAleCR** [comment]
Hi, I am looking further into this, since the way you are approaching the test seems to be the correct one. I will get back to you ASAP with a solution. Cheers and thanks for the issue!

**Comment by CodingAleCR** [comment]
Dang it! I remembered why you can't do that as of right now ☹️. So, since the client is actually not implemented via interfaces we need to provide one or provide a client to be mocked. I am working hard to add testing and refactoring the bits and pieces that are affected by this so we can actually start using the package in the way it's supposed to work. I am so sorry for the inconveniences that this has brought for you.
